### ISSUE TITLE
error expected primary expression before <<

### ISSUE THREAD

**Issue by j4rv1s1** [aminroosta/sqlite_modern_cpp#115]
so i wrote this c++ really fast and i got some errors when compiled, can you help me find the solution? tnx

compiler errors:
```
wrapper.cpp: In function ‘int main()’:
wrapper.cpp:19:11: error: expected primary-expression before ‘<<’ token
           << var2;
           ^~
wrapper.cpp:20:11: error: expected primary-expression before ‘<<’ token
           << var3;
           ^~
wrapper.cpp:21:11: error: expected primary-expression before ‘<<’ token
           << var4;
           ^~
```

and this is the code:

```c++
#include <iostream>
#include <sqlite_modern_cpp.h>
using namespace std;
using namespace sqlite;

int main() {

  try {
    database db("test.db");


    string var1 = "test";
    string var2 = "test1";
    string var3 = "test2";
    string var4 = "test3";

    db << u"insert into COMPANY (ID,NAME,AGE,ADDRESS) values (?,?,?);"
          << var1;
          << var2;
          << var3;
          << var4;


    cout << "The new record got assigned id " << db.last_insert_rowid() << endl;

  }

catch (exception& e) {
  cout << e.what() << endl;

}

}
```

**Comment by zauguin** [comment]
The error is what the compiler says, there is no expression in front of the operator `<<` in lines 19-21.
You indented `<< var2` etc., but they no longer belong to the former statement, because the statement ends with the `;` after `<< var1`.
You can find things like this by using your editor or tools like _clang-format_ to fix the indention of your code.

This issue tracker is for issues in the `sqlite_modern_cpp` project, not for general programming advice. If you program "really fast" and it doesn't compile, you should take some time to search for the error. If you can't find it, I can recommend asking on sites like [StackOverflow](https://stackoverflow.com/).

**Comment by j4rv1s1** [comment]
Ok yeah i forgot to delete the " ; ". now it compiles and the code is inside the same folder where my test.db is. i get an error "SQL logic error or missing database" any tip?
