### ISSUE TITLE
Just wondering why use UTF-16 instead of UTF-8?

### ISSUE THREAD

**Issue by unphased** [aminroosta/sqlite_modern_cpp#20]
Hi, this isn't a problem or anything, I am just reading the code in order to figure out how I wanted to extend it and I noticed that UTF-16 is being used and I am simply curious about why this was chosen. 

The general opinion seems to be that UTF-16 isn't as [appealing](http://www.ohadsoft.com/2014/11/should-you-use-stdstring-stdu16string-or-stdu32string/)

**Comment by unphased** [comment]
Sorry this was a really misguided question, I believe you do have overloads and UTF-8 is handled by default

**Comment by Killili** [comment]
The question is not as misguided as you think ;)

It turned out that we had a problem in older versions where we used wstring and found out that Windows uses 2 byte per wchar and Linux 4 byte per wchar and both call it a wstring. But sqlite only understands the 2 byte variant. So we needed to explicitly use u16string here to avoid that bug.

**Comment by unphased** [comment]
Cool, yeah that's pretty much the tip of the iceberg with this stuff and sticking with UTF-8 is pretty much the only sane thing left to consider these days.
