### ISSUE TITLE
VS 2013 error C2440: '<function-style-cast>'

### ISSUE THREAD

**Issue by szaboa** [aminroosta/sqlite_modern_cpp#41]
Hi, when I am compiling I get errors like:
`Error	1	error C2440: '<function-style-cast>' : cannot convert from 'const char *' to 'sqlite::exceptions::error'	...\hdr\sqlite_modern_cpp.h	63	1`

Could you suggest a solution?

**Comment by Killili** [comment]
Hi,
the only thing that i can think of is a definition of sqlite::exceptions::error somewhere in youre code that leaks into our namespace. And gets used at that point instead of our class that has a appropriate constructor. But yours is trying to use its copy constructor instead.

I can remember some trouble with the sqlite3_errstr() function but i think thats not it here.

**Comment by aminroosta** [comment]
@szaboa Which compiler are you using? which version?
Are you able to run examples in the test folder?

**Comment by szaboa** [comment]
I am using Visual Studio 2013, Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x86, I am going to test if I am able to run the examples today, and I will get back to you.

**Comment by aminroosta** [comment]
I am almost sure we don't support vs 2013 anymore.
Any chance you could use vs 2015 instead?
You can try previous releases if you are stuck with vs 2013 though.

**Comment by szaboa** [comment]
I am able to use after commenting out the different exception types and just throw `sqlite_exception(sqlite3_errstr(error_code));` in every case.  And also needed to write a macro for `noexcept` usage (like [this](http://stackoverflow.com/a/18387764/1949520)). I am going to use it with these modifications, until I switch to VS 2015.

**Comment by aminroosta** [comment]
Cool :-)
I've updated the title i case someone else have the same problem with VS 2013.
