### ISSUE TITLE
blob handle

### ISSUE THREAD

**Issue by alext234** [aminroosta/sqlite_modern_cpp#69]
Would it be nice if there is support for blob handle (e.g. using sqlite3_blob_open and sqlite3_blob_read)? Some blobs can be quite big so I am interested to query only the top few bytes.

**Comment by aminroosta** [comment]
@alext234 

I found this.
http://www.sqlite.org/lang_corefunc.html#substr

**substr(X,Y,Z)**  
**substr(X,Y)**

*The substr(X,Y,Z) function returns a substring of input string X that begins with the Y-th character and which is Z characters long. If Z is omitted then substr(X,Y) returns all characters through the end of the string X beginning with the Y-th. The left-most character of X is number 1. If Y is negative then the first character of the substring is found by counting from the right rather than the left. If Z is negative then the abs(Z) characters preceding the Y-th character are returned. If X is a string then characters indices refer to actual UTF-8 characters. **If X is a BLOB then the indices refer to bytes**.*

So something like this should work (i have not tested this, it's just my guess)
```c++
db << "CREATE TABLE person (name TEXT, numbers BLOB);";
db << "INSERT INTO person VALUES (?, ?)" << "bob" << vector<int> { 1, 2, 3, 4, 5, 6, 7};       
vector<int> numbers_bob;
db << "SELECT SUBSTR(numbers,?,?) from person where name = ?;"
    << 8 /* offset */ << 12 /* count */ <<  "bob" >> numbers_bob;
// numbers_bob should become { 3, 4, 5}
```

Alex if this or something similar worked for you please add the your code here.
If `SUBSTR` didn't help, update the issue and we will think of another way to address this :-)

**Comment by alext234** [comment]
@aminroosta  substr works fine for me. Thanks :+1:
