### ISSUE TITLE
sqlite_exception ... access to error code?

### ISSUE THREAD

**Issue by mtissington** [aminroosta/sqlite_modern_cpp#80]
When a sqlite_exception is thrown how do I access the error code?

can you make error_code available?

Thanks.

**Comment by zauguin** [comment]
The error code can't be a accessed directly, you can differentiate the errors by the type and the message. 
Why do you need the codes?

**Comment by mtissington** [comment]
Hmm, you have made row id available, surly its straight forward to make the error_code available?

When I catch-all exceptions using sqlite_exception, using error_code I could have a simple switch statement.

How is type available in the catch-all sqlite_exception?

**Comment by mtissington** [comment]
Unless I'm missing something the sqlite_exception is a struct that contains a string. It would be of great help
to have the struct also contain the error code ... :)

**Comment by zauguin** [comment]
Just in case you still need this: I created a PoC ([zauguin/errorcodes](/zauguin/sqlite_modern_cpp/tree/errorcodes)) where the exception object contains a `get_code()` method to access the code.
But I do not think that this is generally useful. Why do you want to catch sqlite_exception and use a switch instead of catching the individual error types?

**Comment by mtissington** [comment]
Thanks ... I used your earlier suggestion and used typeid(object) instead. For all exceptions I need to just log the error and no_row I need to do a little extra processing. It's been a long day!

**Comment by mtissington** [comment]
Having thought about this I think using get_code() is cleaner. Using typeid(e) seems to me to be a cludge to get the information.

I hope you merge this into master :)

**Comment by zauguin** [comment]
@aminroosta What do you think about this?

**Comment by polesapart** [comment]
An IMHO cleaner (but API-breaking) change would be to change the sqlite_exception constructor to something like:
    
    sqlite_exception(char ecode): runtime_error(sqlite3_errstr(ecode)), code(ecode) {}
    

Which would allow the specific exceptions to be initialized by (i.e.):
   
    if(error_code == SQLITE_ERROR) throw exceptions::error(error_code);
    

instead of:
    
   if(error_code == SQLITE_ERROR) throw exceptions::error(sqlite3_errstr(error_code), error_code);
    

But perhaps that's too disruptive just for having cosmetics.

**Comment by zauguin** [comment]
Actually the old changing was API-breaking already, because you had to pass the errorcode.
So I pushed a change which adds this as a second constructor.

**Comment by aminroosta** [comment]
Looks good to me, Thanks @zauguin!
Can you write a little documentation in the README file :-)
