### ISSUE TITLE
get_sql() returns empty string

### ISSUE THREAD

**Issue by mtissington** [aminroosta/sqlite_modern_cpp#91]
I'm creating and using a prepared statement auto ps = db << 'select field from mytable';  etc,
For testing I changed the field name to an incorrect value. An exception was correctly thrown. However get_sql() returned an empty string.

Am I missing something?

**Comment by zauguin** [comment]
Is the exception thrown when you create or when you use the statement? Is the statement UTF-16 encoded?

**Comment by zauguin** [comment]
Maybe you can create a [gist](https://gist.github.com/) which shows the failing code?

**Comment by mtissington** [comment]
It occurs when I use the statement and it's utf-16

**Comment by mtissington** [comment]
does this help 
[<script src="https://gist.github.com/mtissington/7c95950c6914fbc8bc34c03ec55051ca.js"></script>](url)

**Comment by zauguin** [comment]
Tip: Please share the "Share" URL and not the embed script of your gists in the future. This makes it easier to open it. Additionally you got the syntax for links backwards.

**Comment by aminroosta** [comment]
@mtissington I updated you comment, but the link still doesn't work :-(

**Comment by aminroosta** [comment]
@zauguin are you sure #92 fixes this?!

**Comment by zauguin** [comment]
@aminroosta Yes, the problem is, that when prepare fails (this happens in this case, because a query plan can't be produced for an invalid column, the query is only appended in the UTF-8 case([the source](https://github.com/aminroosta/sqlite_modern_cpp/blob/master/hdr/sqlite_modern_cpp.h#L224-L232))
In the UTF-16 case we would have to convert the statement to UTF-8, which I tried to avoid.
#92 does this conversion always, because this shouldn't change anything in the regular case but avoids a double conversion in the exceptional case.

**Comment by zauguin** [comment]
@mtissington I updated your comment too, now your link works.

**Comment by mtissington** [comment]
Thanks - A little new to posting gists.
