### ISSUE TITLE
multiple statements fail - expected behavior?

### ISSUE THREAD

**Issue by samhatchett** [aminroosta/sqlite_modern_cpp#99]
I've noticed that when feeding in multiple semicolon-delimited statements as part of a single string, only the first statement is actually executed. for example:

```
database db("test.db");
db << "create table 'data'('col' integer); create table 'meta'('col' integer);";
// only the first table is created
```

The practical use case here is executing a whole bunch of statements to setup the schema when creating a new db.

if I split the string on semicolons and feed each string in, everything works. If this is expected behavior, it should probably be documented - even though I notice the the usage idioms only show examples of single statements.

**Comment by zauguin** [comment]
Yes, this is expected behaviour. Documentation and errors should be added.

When you emulate this by splitting on semicolons take care, there might be semicolons in a single statement.
I do not think this is a good idea in general, but you can try [code like this](https://gist.github.com/zauguin/a2cb8f8f7d6915086f2f780be4b6cdba) instead if you really need it. All results will be ignored, if something fails you can't easily trace which commands were executed.
